/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipisa.proyectofinal.frontend;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Luis Martinez
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    private Problemas po;
    private RegFactura Fi;
    private RegUsuario us;
    private RegFacturacion nm;
    private RegProducto rp;
    private RegSuplidor rs;
    private RegCliente rc;
    private RegEmpleado re;
    private RegCategoria rcat;
    private PagoFacPendi pfp;
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Productos = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        Suplidores = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenuItem();
        Categorias = new javax.swing.JMenuItem();
        Usuario = new javax.swing.JMenuItem();
        Facturas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Facturacion = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/Sin-título-2.gif"))); // NOI18N

        dp.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1385, Short.MAX_VALUE)
                .addContainerGap())
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/compras (1).png"))); // NOI18N
        jMenu1.setText("Busqueda y Manejo");

        Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/paquete (1).png"))); // NOI18N
        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        jMenu1.add(Productos);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/certificado.png"))); // NOI18N
        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jMenu1.add(Clientes);

        Suplidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/apoyar.png"))); // NOI18N
        Suplidores.setText("Suplidores");
        Suplidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuplidoresActionPerformed(evt);
            }
        });
        jMenu1.add(Suplidores);

        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/red.png"))); // NOI18N
        Empleados.setText("Empleados");
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(Empleados);

        Categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/agenda.png"))); // NOI18N
        Categorias.setText("Categorias");
        Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriasActionPerformed(evt);
            }
        });
        jMenu1.add(Categorias);

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/jefe (1).png"))); // NOI18N
        Usuario.setText("Usuarios");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(Usuario);

        Facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/carpeta.png"))); // NOI18N
        Facturas.setText("Facturas de los clientes");
        Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturasActionPerformed(evt);
            }
        });
        jMenu1.add(Facturas);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/tienda-online.png"))); // NOI18N
        jMenu3.setText("Procesos");

        Facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/dinero.png"))); // NOI18N
        Facturacion.setText("Facturacion");
        Facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturacionActionPerformed(evt);
            }
        });
        jMenu3.add(Facturacion);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/bolsa-de-dinero.png"))); // NOI18N
        jMenuItem1.setText("Pagos pentientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/sitio-web.png"))); // NOI18N
        jMenu4.setText("Ayuda y/o Problemas");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
      
        rp = new RegProducto();
        this.dp.add(rp);
        try {
            rp.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        rp.show();
     
    }//GEN-LAST:event_ProductosActionPerformed

    private void SuplidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuplidoresActionPerformed
      
        rs = new RegSuplidor();
        this.dp.add(rs);
        try {
            rs.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        rs.show();
    }//GEN-LAST:event_SuplidoresActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed

        rc = new RegCliente();
        this.dp.add(rc);
        try {
            rc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        rc.show();
    }//GEN-LAST:event_ClientesActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        
        re = new RegEmpleado();
        this.dp.add(re);
        try {
            re.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        re.show();
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriasActionPerformed
        rcat = new RegCategoria();
        
        this.dp.add(rcat);
        try {
            rcat.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        rcat.show();
        
    }//GEN-LAST:event_CategoriasActionPerformed

    private void FacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturacionActionPerformed
        // TODO add your handling code here:
        nm = new RegFacturacion();
        
        this.dp.add(nm);
        try {
            nm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        nm.show();
    }//GEN-LAST:event_FacturacionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
        us = new RegUsuario();
        
        this.dp.add(us);
        try {
            us.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        us.show();
    }//GEN-LAST:event_UsuarioActionPerformed

    private void FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturasActionPerformed
        // TODO add your handling code here:
        Fi = new RegFactura();
        
        this.dp.add(Fi);
        try {
            Fi.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        Fi.show();
    }//GEN-LAST:event_FacturasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         pfp = new PagoFacPendi();
        
        this.dp.add(pfp);
        try {
            pfp.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        pfp.show();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        po = new Problemas();
        
        this.dp.add(po);
        try {
            po.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        po.show();
    }//GEN-LAST:event_jMenu4MouseClicked

   

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Categorias;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Empleados;
    private javax.swing.JMenuItem Facturacion;
    private javax.swing.JMenuItem Facturas;
    private javax.swing.JMenuItem Productos;
    private javax.swing.JMenuItem Suplidores;
    private javax.swing.JMenuItem Usuario;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
