/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipisa.proyectofinal.frontend;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Luis Martinez
 */
public class Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
     private final Timer t;
     private final ActionListener ac;
    int x =0;
     
    public Prueba() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        ac = new ActionListener() {
            
            
            @Override
            public void actionPerformed(ActionEvent ae) {
           
                try {
                     x=x+1;
              
                    jProgressBar1.setValue(x);
                    jProgressBar1.setStringPainted(true);
                  
                } catch (Exception e) {
                }
              
                
                if (jProgressBar1.getValue()== 100) {
                    
                    dispose();
                    Abrir();
                    t.stop();

                    
                }
             
              }
            
        };
        
        t = new Timer(38, ac);
        t.start();
    }
    
    public void Abrir(){
        MainApp app = new MainApp();
                
                app.setExtendedState(MAXIMIZED_BOTH);
                app.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setEnabled(false);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipisa/proyectofinal/resources/Carga.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -60, 740, 580));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 214, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
